SELECT ?item ?itemLabel ?startYear ?endYear ?sitelinks WHERE {
  ?item
    wdt:P31/wdt:P279* wd:Q6881511; # enterprise (covers companies, businesses, brands)
    wdt:P571 ?startDate; # inception
    wikibase:sitelinks ?sitelinks;
    rdfs:label ?itemLabel.
  OPTIONAL { ?item wdt:P576 ?endDate. } # dissolution
  FILTER(LANG(?itemLabel) = "en")
  FILTER(?sitelinks >= 40)
  BIND(YEAR(?startDate) AS ?startYear)
  BIND(IF(BOUND(?endDate), STR(YEAR(?endDate)), "") AS ?endYear)
}
ORDER BY DESC(?sitelinks)
LIMIT 500
