SELECT ?item ?itemLabel ?startYear ?endYear ?sitelinks WHERE {
  ?item
    wdt:P31/wdt:P279* wd:Q5398426; # television series
    wdt:P580 ?startDate; # start time of broadcast
    wikibase:sitelinks ?sitelinks;
    rdfs:label ?itemLabel.
  OPTIONAL { ?item wdt:P582 ?endDate. } # end time of broadcast
  FILTER(LANG(?itemLabel) = "en")
  FILTER(?sitelinks >= 25)
  BIND(YEAR(?startDate) AS ?startYear)
  BIND(IF(BOUND(?endDate), STR(YEAR(?endDate)), "") AS ?endYear)
}
ORDER BY DESC(?sitelinks)
LIMIT 500
